### ISSUE TITLE
P:S lags after certain number of moves in edge and chrome

### ISSUE THREAD

**Issue by Toomber** [ClementSparrow/Pattern-Script#71] opened 2023-10-24 11:27 UTC
A while ago someone pointed out that my game Level (https://toombler.itch.io/level, https://clementsparrow.github.io/Pattern-Script/src/play.html?p=88371b95c9897d33a65f3f748ae7474b) lags for them after some number of moves. I checked it out and it did for me too (even though it was fine when I released the game in Dec 2022). Here is a screenshot of my chrome profiler when the game lags. It does this in the embedded version, the editor, as well as the external link. Also, the lag persists even after pressing r to restart, and only goes away after refreshing the page.
![Capture](https://github.com/ClementSparrow/Pattern-Script/assets/58906286/b410e7ff-2511-4409-a71e-cbc01551fb26)

Recently I started making a new game in P:S and I ran into the same lag issue. Here is a pretty minimal example, just a big ish level with a player walking around. 
[minimalPatternScriptSlowdownExample.txt](https://github.com/ClementSparrow/Pattern-Script/files/13113806/minimalPatternScriptSlowdownExample.txt)
Here is a video of it slowing down in edge: https://youtu.be/GnQzSUsH5Iw

Here is the practical example of the game I'm trying to make, where I commented most things out and it still massively slows down 
[anotherPatternScriptSlowdownExample.txt](https://github.com/ClementSparrow/Pattern-Script/files/13113910/anotherPatternScriptSlowdownExample.txt)

I'm pretty sure that the slowdown only happens in edge and chrome, not firefox (I am on windows 10). 

I hope this is helpful information to try and solve this issue, I'd love to be able to keep using P:S because I find it really useful :)

**Comment by david-pfx** [comment] 2023-10-24 12:23
I'd like to help diagnose this problem, but I'm not sure how to do that. 

Is it memory? Have you done monitoring of that?

**Comment by ClementSparrow** [comment] 2023-10-24 13:02
Thanks for the report!

Unfortunately, I will not have the time to investigate this issue before next week, so if @david-pfx wants to help finding the cause of the lag, his help will be welcome :-)

From your screenshots, I suspect it comes from the change in how re-scaling is done, that I made maybe one year ago. I knew it could have performance issues on games that have a large visual screen (either because of a large `sprite_size` or because of large levels), but I tested on the existing games that I know without any issue. It's likely that I only tested with Firefox and Safari, though. Maybe also Chrome and Edge changed something in their APIs that affect this issue. And it's even more likely that Chrome is a shitty browser that nobody should use.

Finally, I want to take this chance to recall everyone that P:S is still considered to be a work in progress and that things can beak. Therefore, it is strongly advised to share your games with the `EXPORT` command rather than with the `SHARE` command. The export feature ensures the game will not be affected by future changes in the engine. At least, you should keep an exported version of your game that works, in case something breaks later ;-)

**Comment by ClementSparrow** [comment] 2023-10-24 13:22
one of the two commits linked just above this comment might be the source of the bug

**Comment by Toomber** [comment] 2023-10-24 14:27
Thanks for the response! No rush on fixing, I don't need it for anything important.
The fact that the exported version on my itch page got this issue after the fact leads me to think it's likely due to a change made by the browsers.

I can try monitor the memory @david-pfx

**Comment by ClementSparrow** [comment] 2023-10-24 14:31
Oh, I did not realize that the version on your itch page was exported. And it's one year younger than the commits I identified as a possible source of the bug, so the bug was not introduced by these commits (but can still be related).

**Comment by Toomber** [comment] 2023-10-25 08:19
@david-pfx I don't think it's memory, I tried to profile and it the heap only came to 3-6mb. But I'm not certain I know how to use chrome's memory profiler.

**Comment by souvey** [comment] 2023-11-11 15:43
Seems like this can be fixed by using `this.canvas.getContext('2d', {willReadFrequently: true})`

**Closed as completed** 2023-11-18 13:36 UTC
Labels: bug, code, games, optimization

**Comment by ClementSparrow** [comment] 2023-11-18 13:38
> Seems like this can be fixed by using `this.canvas.getContext('2d', {willReadFrequently: true})`

Thanks for the tip. I actually added this in the dev branch some time ago and forgot to propagate it to the main branch… It seems to solve the issue but I cannot test on all systems, so, everybody, let me know if the lag still happens on some systems/games :-)

**Comment by Toomber** [comment] 2023-12-16 11:19
Thanks, this seems to have fixed the problem perfectly! Sorry for not checking this out sooner.
